회원가입 로그인 기능 구현
wecode-bootcamp-korea/10-bigstar-pharmacy-backend pull request #4
Opened 2020-07-23 23:41 UTC by yotae07

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)   
로그인, 회원가입 구현했습니다.    
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
백앤드에서도 입력제한사항을 만들었습니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-24 06:48 UTC, evergreen-david requested changes

2020-07-24 06:48 UTC, evergreen-david commented on user/views.py
> +                email_bool  = bool(re.search("[a-zA-Z0-9]+$", email_check[0]))
validation 하는 람다함수 만들어서 정리 부탁 드립니다.
```
def validate(email or password):
    validate_condition = [
        lambda s: code,
        lambda s: code,
        lambda s: code,

    ]
    is_email_valid = True
    for validator in validate_condition:
        if not validator(email):
            return False
    return is_email_valid
```

2020-07-24 06:49 UTC, evergreen-david commented
tests.py 유닛 테스트가 구현안되어 있는데 확인 부탁 드립니다.
예를들어 회원가입과 로그인 엔드포인트를구현하면
SignIn 유닛테스트,
SignUp 유닛테스트에 대한 유닛테스트2개가 필요합니다.

2020-07-28 07:38 UTC, soheon-lee commented on user/urls.py
> +from .views      import SignUpView, SignInView
```suggestion
from .views      import (
    SignUpView, 
    SignInView
)
```

2020-07-28 07:38 UTC, soheon-lee commented on user/utils.py
> +import json, jwt
```suggestion
import json
import jwt
```

2020-07-28 07:38 UTC, soheon-lee commented on user/utils.py
> +from pilly.settings     import SECRET_KEY, ALGORITHM
```suggestion
from pilly.settings     import (
    SECRET_KEY, 
    ALGORITHM
)
```

2020-07-28 07:38 UTC, soheon-lee commented on user/views.py
> +import json, bcrypt, jwt, re
```suggestion
import json
import bcrypt
import jwt
import re
```

2020-07-28 07:38 UTC, soheon-lee commented on user/views.py
> +                print('asfd')
사용하지 않는 주석 제거해주세요

2020-07-28 07:38 UTC, soheon-lee commented on user/views.py
> +                    print('ccc')
사용하지 않는 주석 제거해주세요

2020-07-28 07:38 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'message': 'INVLID_INPUT'}, status=401)
비밀번호와 이메일의 오류를 구분하여 알려주는 것은 보안에 취약해집니다. 두 경우의 메세지를 통일해주세요.

2020-07-30 03:00 UTC, soheon-lee commented on user/views.py
> +            contact = data.get("context")
`context` 가 키 이름인가요?

2020-07-30 03:00 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'message': 'INVALID_INPUT'})
`return`이 여기에 있으면 `email`이나 `contact`가 있는지 없는지 여부에 아무 상관없이 모든 경우에 INVALID_INPUT이 뜨게 됩니다. 이 이후에 그 어떤 코드로도 접근할 수가 없게됩니다. 한 번 더 확인해주세요. 로그인되던가요?

2020-07-30 03:00 UTC, soheon-lee commented on user/views.py
> +                user = user_qs[0]
`get( )`메소드 사용해주세요

2020-07-30 07:57 UTC, evergreen-david commented
address 안된 커멘트 확인해 주시고 수정 부탁 드립니다.
https://github.com/wecode-bootcamp-korea/10-bigstar-pharmacy-backend/pull/4/files#r459828755
https://github.com/wecode-bootcamp-korea/10-bigstar-pharmacy-backend/pull/4/files#r459828793

2020-07-30 08:53 UTC, merged