Feature/survey
wecode-bootcamp-korea/10-bigstar-pharmacy-backend pull request #7
Opened 2020-07-28 06:42 UTC by yotae07

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
설문조사 models.py 및 views.py기능 만들었습니다.
         
		 
## 수정 사항들 자세한 내용
설문조사 초기사항 구축

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-28 07:50 UTC, soheon-lee commented on survey/models.py
> +    update_at    = models.DateTimeField(auto_now = True)
`=`을 기준으로 코드 정렬해주세요
```suggestion
    question     = models.CharField(max_length=256)
    sub_quesion   = models.CharField(max_length=256)
    userquestion = models.ManyToManyField(User, through='UserQuestion', related_name = 'user_question')
    created_at   = models.DateTimeField(auto_now_add = True)
    updated_at    = models.DateTimeField(auto_now = True)
```

2020-07-28 07:50 UTC, soheon-lee commented on survey/models.py
> +    update_at   = models.DateTimeField(auto_now = True)
```suggestion
    updated_at   = models.DateTimeField(auto_now = True)
```

2020-07-28 07:50 UTC, soheon-lee commented on survey/urls.py
> +from .views      import SurveyView, SurveyResultView
```suggestion
from .views      import (
    SurveyView, 
    SurveyResultView
)
```

2020-07-28 07:50 UTC, soheon-lee commented on survey/views.py
> +from .models      import Question, Answer, UserQuestion, Result
```suggestion
from .models      import (
    Question, 
    Answer, 
    UserQuestion, 
    Result
)
```

2020-07-28 07:50 UTC, soheon-lee commented on survey/views.py
> +                    user_select_list.append(user_select_answer)
리스트 컴프리헨션으로 변환해주세요

2020-07-28 07:50 UTC, soheon-lee commented on survey/views.py
> +                user             = UserQuestion.objects.filter(user = user.id)
이미 user 정보를 데코레이터를 통해 확인하고 객체를 가져왔는데 다시 `user.id`를 이용해 필터링하는 이유가 있나요?

2020-07-28 07:50 UTC, soheon-lee commented on user/models.py
> +    update_at     = models.DateTimeField(auto_now = True)
```suggestion
    updated_at     = models.DateTimeField(auto_now = True)
```

2020-07-28 07:50 UTC, soheon-lee commented on user/urls.py
> +from .views      import SignUpView, SignInView
```suggestion
from .views      import (
    SignUpView, 
    SignInView
)
```

2020-07-30 08:09 UTC, evergreen-david commented
@yotae07 커멘트 adress 되셨으면 resolve conversation 해주세요!

2020-07-30 08:11 UTC, evergreen-david requested changes

2020-07-30 08:11 UTC, evergreen-david commented on survey/models.py
> +    userquestion = models.ManyToManyField(User, through='UserQuestion', related_name = 'user_question')
```suggestion
    user_question = models.ManyToManyField(User, through='UserQuestion', related_name = 'user_question')
```

2020-07-30 08:11 UTC, evergreen-david commented on survey/views.py
> +    for key in result.keys():
뷰에서 이렇게 하드코딩 데이터를 넣지말고 데이터베이스에 저장해서 관계를 사용하여 쿼리해서 가져오게 구현 부탁 드립니다.

2020-07-30 08:29 UTC, yotae07 commented on survey/views.py
> +    for key in result.keys():
저희 시간이 부족할거 같아 랜덤함수로 대체했습니다

2020-07-30 11:28 UTC, evergreen-david commented on survey/views.py
> +    for key in result.keys():
@yotae07 
태성님 현업에서 시간이 부족하다고 해서 이렇게 하드코딩해서 구현하게 되면 안됩니다.
만약 오늘까지 구현해보고 정 안되면 로컬 버전으로 데모하고 제대로 구현해서 반영해주세요! 
왜냐하면 나중에 이코드가 나의 코드로 포트폴리오에 쓰이고 실제로 구현한 깃헙의 코드를 보는 회사도 있기 때문에 수정 부탁 드리겠습니다.

2020-07-30 11:39 UTC, evergreen-david approved these changes

2020-07-30 11:40 UTC, merged