Feature/payment
wecode-bootcamp-korea/10-bigstar-pharmacy-backend pull request #8
Opened 2020-07-28 13:28 UTC by JunGyver

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-30 08:15 UTC, evergreen-david requested changes

2020-07-30 08:15 UTC, evergreen-david commented on payment/models.py
> +    cardnkakao = models.CharField(max_length=20, null=True)
card and kakao 라는 의미인가요 ? 그렇다면 11라인처럼 card_kakao 라고 하는게 나을것같아요

2020-07-30 08:15 UTC, evergreen-david commented on payment/urls.py
> +    path('mypilly', MyPilly.as_view(), name='mypilly'),
View를 상속하고 있고 model 클래스와 다르게 View 클래스임을 명확하게 하기 위해서 클래스 이름 끝에 View를 붙여주세요
```suggestion
    path('my-pilly', MyPillyView.as_view(), name='mypilly'),
```

2020-07-30 08:15 UTC, evergreen-david commented on payment/views.py
> +                    #print(f'{i}',data_set)
프린트 문들은 정리해주세요.

2020-07-30 08:15 UTC, evergreen-david commented on payment/views.py
> +
파일의 끝은 한줄만 남기고 전부 삭제해서 정리해주세요.

2020-07-30 08:15 UTC, evergreen-david commented on product/admin.py
> +admin.site.register(Product_detail)
admin은 커멘트 드린대로 정리해주시고 settings에서도 정리해주세요.

2020-07-30 09:16 UTC, JunGyver commented on payment/models.py
> +    cardnkakao = models.CharField(max_length=20, null=True)
수정했습니다.

2020-07-30 09:17 UTC, JunGyver commented on payment/urls.py
> +    path('mypilly', MyPilly.as_view(), name='mypilly'),
붙여서 수정했습니다.

2020-07-30 09:17 UTC, JunGyver commented on payment/views.py
> +                    #print(f'{i}',data_set)
프린트문 지웠습니다.

2020-07-30 09:17 UTC, JunGyver commented on payment/views.py
> +
삭제했습니다.

2020-07-30 09:17 UTC, JunGyver commented on product/admin.py
> +admin.site.register(Product_detail)
정리했습니다.

2020-07-30 11:45 UTC, evergreen-david commented
@JunGyver 님 컨플릭트 수정 부탁 드립니다.

2020-07-30 11:50 UTC, evergreen-david requested changes

2020-07-30 11:50 UTC, evergreen-david commented on product/views.py
> +#                   cart=0
주석 정리 부탁 드립니다.

2020-07-30 11:50 UTC, evergreen-david commented on product/views.py
> +#from cart.models import Cart
주석 정리 부탁 드립니다.

2020-07-30 11:52 UTC, evergreen-david commented
@JunGyver 님 컨플릭트 해결해주시고 유닛테스트가 없는데 확인 부탁 드리겠습니다.

2020-07-30 12:17 UTC, JunGyver commented on product/views.py
> +#                   cart=0
정리했습니다.

2020-07-30 12:17 UTC, JunGyver commented on product/views.py
> +#from cart.models import Cart
정리했습니다.

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +        print(cart_info)
보다 깔끔한 코드를 위해 print문은 삭제해주세요

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +        prices        = '-'.join(price)
코드 간격 맞춰주세요

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +        print(cart_info, item)
삭제해주세요

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +                ).save()
```suggestion
            if data['card_kakao']=='credit':
                Payment(
                    name     = data['name'],
                    contact          = data['contact'],
                    post_number      = data['post_number'],
                    address_street   = data['address_street'],
                    address_detail   = data['address_detail'],
                    customer_request = data['customer_request'],
                    card_number      = data['card_number'],
                    expired_month    = data['expired_month'],
                    expired_year     = data['expired_year'],
                    birth            = data['birth'],
                    card_password    = data['card_password'],
                    user_id          = personal_info.id,
                    purchased_item   = items,
                    price            = prices,
                    count            = counts,
                    total_price      = data['totalPrice'],
                    points           = 0,
                    back_image       = rgbs,
                    pill_image       = imgs,
                    card_kakao       = data['card_kakao']
                ).save()
```

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +            print(cart_info)
삭제해주세요

2020-07-31 01:34 UTC, soheon-lee commented on payment/views.py
> +                ).save()
클래스의 속성들만 추가로 들여쓰기 한 칸 해주세요 보다 파이썬 다운 코드 스타일입니다.

2020-07-31 01:34 UTC, soheon-lee commented on product/views.py
> +#                   cart=0
사용하지 않는 주석은 모두 삭제해주세요

2020-07-31 01:45 UTC, JunGyver commented on payment/views.py
> +        print(cart_info)
삭제했습니다.

2020-07-31 01:45 UTC, JunGyver commented on payment/views.py
> +        prices        = '-'.join(price)
간격 맞쳤습니다.

2020-07-31 01:45 UTC, JunGyver commented on payment/views.py
> +                ).save()
수정했습니다.

2020-07-31 01:46 UTC, JunGyver commented on product/views.py
> +#                   cart=0
수정했습니다.

2020-07-31 01:53 UTC, merged