Feature/review
wecode-bootcamp-korea/10-bigstar-pharmacy-backend pull request #9
Opened 2020-07-28 13:35 UTC by JunGyver

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-30 08:03 UTC, evergreen-david requested changes

2020-07-30 08:03 UTC, evergreen-david commented on product/admin.py
> +admin.site.register(Product_detail)
admin register 는 왜 등록하신건가요 ? admin은 안써도 되니 디버깅 용도로만 쓰고 정리 부탁 드립니다.

2020-07-30 08:03 UTC, evergreen-david commented on product/views.py
> +#from cart.models import Cart
주석 정리해주세요.

2020-07-30 08:03 UTC, evergreen-david commented on product/views.py
> +#                   cart=0
여기도 같은 커멘트 드립니다.!

2020-07-30 08:03 UTC, evergreen-david commented on product/views.py
> +        data_set=[]
data_set,37 라인에서 append 하지말고 -> 리스트 컴프리헨션으로 구현 부탁 드립니다.

2020-07-30 10:22 UTC, JunGyver commented on product/views.py
> +#from cart.models import Cart
주석 정리했습니다.

2020-07-30 10:22 UTC, JunGyver commented on product/views.py
> +#                   cart=0
정리했습니다. 내용이 수정되었습니다. 확인 부탁드려요

2020-07-30 10:23 UTC, JunGyver commented on product/views.py
> +        data_set=[]
카트에 담긴 여부 보내는 과정에서 어려움이 있어 리스트 컴프리핸션 구현에 막혔는데요. 설명 부탁드려도 될까요?

2020-07-30 11:48 UTC, evergreen-david requested changes

2020-07-30 11:48 UTC, evergreen-david commented on review/views.py
> +
파일의 끝은 한줄만 남기고 정리 부탁 드립니다.

2020-07-30 11:48 UTC, evergreen-david commented on product/views.py
> +                                 'cart':0})
except 에서 정상적인 데이터를 리턴하면 안됩니다. except 는 말그대로 예외처리기 때문에 에러코드를 보내야 합니다.
여기서 작성하신 로직은 try에서 분기해서 처리해주세요.

2020-07-30 12:18 UTC, JunGyver commented on product/admin.py
> +admin.site.register(Product_detail)
정리했습니다.

2020-07-30 12:18 UTC, JunGyver commented on review/views.py
> +
정리했습니다.

2020-07-30 12:34 UTC, JunGyver commented on product/views.py
> +                                 'cart':0})
안에서 조건을 주어 수정하였습니다.

2020-07-31 02:04 UTC, soheon-lee commented on pilly/urls.py
>      path('', include('cart.urls')),
url을 앱 urls.py 에 붙여놓으셨네요. 오류는 나지 않지만 통상적으로 path메소드에 파라미터로 앱 이름을 넣어줍니다. 추후 리팩토링 해주세요

2020-07-31 02:06 UTC, merged